### ISSUE TITLE
Please Follow Open Source Licenses and Copyright Law

### ISSUE THREAD

**Issue by davecom** [T-parrish/LeetCode#1]
You can't just take the code from someone else's work without citing it and following the license. You certainly can't copy and paste text from a book. Please:
A) Remove any text copy and pasted from my book
B) If you want to keep using the code, please follow the license terms (Apache license) of the code:
https://github.com/davecom/ClassicComputerScienceProblemsInPython/blob/master/LICENSE

Thank you.

**Comment by T-parrish** [comment]
Oh my gosh I’m so sorry, I’ll take it down immediately.

I really truly apologize - your book has been incredibly helpful for me and
I wasn’t thinking properly.

Best,
Taylor

**Comment by T-parrish** [comment]
I’ve taken them down. Many apologies for the error on my part.

**Comment by davecom** [comment]
It's okay, don't worry about it. I know your intent wasn't to do anything wrong. I just every now and then do searches to see where it's being used and when I notice copies of its content being distributed improperly I mention it. Most people don't know and don't realize it's even wrong. It's really a futile effort because books today are so heavily pirated... but you know us authors of technical books make a very small royalty so every bit we can do to defend our rights is worth it. Best wishes to you and thanks for reading the book.
